language: node_js
node_js:
  - 11

notifications:
  email: false

before_script:
  - npm install && npm run build

script: 
  - npm start > /dev/null &
  - sleep 10; npm test

after_success:
  - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725